services:
  postgresql:
    image: postgres:17
    container_name: pikaw-postgresql
    environment:
      POSTGRES_DB: pikaw
      POSTGRES_USER: pikaw
      POSTGRES_PASSWORD: pikaw
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pikaw" ]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - pikaw-network
  victoriametrics:
    image: victoriametrics/victoria-metrics:v1.131.0
    container_name: victoriametrics
    command:
      - "-retentionPeriod=7d"  # 保留 7 天数据
      - "-storageDataPath=/victoria-metrics-data"
      - "-httpListenAddr=:8428"
    ports:
      - "127.0.0.1:8428:8428"  # API, PromQL, insert, select
    volumes:
      - ./data/vmdata:/victoria-metrics-data
    restart: always
    networks:
      - pikaw-network
  pikaw:
    image: wangyanbiao/pikaw:latest
    container_name: pikaw-server
    volumes:
      - ./config.yaml:/app/config.yaml
    # 开启 Geo 配置后打开下面的配置
    #  - ./GeoLite2-City.mmdb:/app/GeoLite2-City.mmdb
    ports:
      - "8080:8080"
    depends_on:
      postgresql:
        condition: service_healthy
      victoriametrics:
        condition: service_started
    restart: always
    dns:
      - 127.0.0.11
      - 8.8.8.8
    networks:
      - pikaw-network

networks:
  pikaw-network:
    driver: bridge

